services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
      - "643:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - fdf-portal-network
networks:
  fdf-portal-network:
    driver: bridge
    